"""Controlled multimodal agent rollout primitives for DataFlow-MM."""

from .contracts import (
    ContentLimits,
    Env,
    EnvironmentSpec,
    EpisodeStep,
    ImageContent,
    Message,
    RuleSpec,
    Scenario,
    ScenarioGenerator,
    TaskArtifact,
    TaskProvider,
    TextContent,
    ToolError,
    ToolResult,
    ToolSpec,
    Trajectory,
    VerificationCheck,
    VerificationResult,
    Verifier,
    validate_content,
)
from .runtime_components import AgentRollout, HostPolicy, HostTools, RolloutConfig
from .serving import (
    GeminiKigressServing,
    ModelServing,
    OpenAICompatibleServing,
    ScriptedServing,
    create_model_serving,
    create_model_serving_from_env,
)
from .storage import (
    JsonTaskProvider,
    JsonTaskStore,
    StatePredicateVerifier,
    TrajectoryStore,
)
from .version import __version__

# Importing the extension package is the explicit registration boundary.
from .operators import (
    AgentMMExploreGenerator,
    AgentMMExploreTreeGenerator,
    AgentMMTrajectoryFilter,
    AgentMMTrajectoryQualityEvaluator,
    AgentMMTrajectoryRefiner,
    AgentMMTrajectorySelector,
    AgentMMTrajectoryVerifier,
)

__all__ = [
    "ContentLimits",
    "AgentRollout",
    "AgentMMExploreGenerator",
    "AgentMMExploreTreeGenerator",
    "AgentMMTrajectoryFilter",
    "AgentMMTrajectoryQualityEvaluator",
    "AgentMMTrajectoryRefiner",
    "AgentMMTrajectorySelector",
    "AgentMMTrajectoryVerifier",
    "EpisodeStep",
    "HostPolicy",
    "HostTools",
    "GeminiKigressServing",
    "ImageContent",
    "Message",
    "JsonTaskStore",
    "JsonTaskProvider",
    "ModelServing",
    "OpenAICompatibleServing",
    "Env",
    "EnvironmentSpec",
    "RuleSpec",
    "Scenario",
    "ScenarioGenerator",
    "TaskProvider",
    "StatePredicateVerifier",
    "ScriptedServing",
    "TextContent",
    "TaskArtifact",
    "ToolError",
    "ToolResult",
    "ToolSpec",
    "Trajectory",
    "TrajectoryStore",
    "VerificationCheck",
    "VerificationResult",
    "Verifier",
    "RolloutConfig",
    "validate_content",
    "create_model_serving",
    "create_model_serving_from_env",
    "__version__",
]
